//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamespaceRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public string title { get; set; }
        public string source { get; set; }
        public string titleImage { get; set; }
        public string content { get; set; }
        public string keywords { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> recommend { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<bool> isDel { get; set; }
        public Nullable<int> hit { get; set; }
        public Nullable<bool> isSwitch { get; set; }
    }
}
