//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Web.Comment {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblcontent;
	protected global::System.Web.UI.WebControls.Label lbladdTime;
	protected global::System.Web.UI.WebControls.Label lblip;
	protected global::System.Web.UI.WebControls.Label lblnewsId;
	protected global::System.Web.UI.WebControls.Label lbldig;
	protected global::System.Web.UI.WebControls.Label lblPid;
	protected global::System.Web.UI.WebControls.Label lblisCheck;
	protected global::System.Web.UI.WebControls.Label lbluserId;


       
    }
}
